name: dart_shelf_lambda
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  aws_lambda_dart_runtime:
    git: https://github.com/awslabs/aws-lambda-dart-runtime.git
dev_dependencies:
  build_runner:

